### ISSUE TITLE
Create code block to read in data from json

### ISSUE THREAD

**Issue by FrostBrianna** [michaeltheedev/Spring23SeniorProjectII#3]

**Comment by mmmoore3** [comment]
Opening JSON file
j = open('Data.json')

#returns JSON as a dictionary
data = json.load(j)

#Iterating through the json list
for i in data['project']:
	print(i)

#closing file
j.close()

**Comment by mmmoore3** [comment]
import json
import pandas as pd

#df = pd.read_json('Data.json')
#print ([['title','definition']])

with open('Data.json', 'r') as f:
    data = json.load(f)

json_formatted_str = json.dumps(data, indent=2)

# Output:
#print(data)
print(data)
print(json_formatted_str)


# Opening JSON file
j = open('Data.json')

# returns JSON as a dictionary
data = json.load(j)

# Iterating through the json list
for i in data['project']:
    print(i)

# closing file
j.close()
